#!/usr/bin/env bash

if [[ -z $PLAN9 ]]; then
	echo "Execute in a PLAN9 environment"
else
	# TODO: Actually download things directly instead or from Dropbox
	LANG_DIR_GO=$PLAN9/langs/go
	if [ -d $LANG_DIR_GO ]; then
		go env -w GOPATH=$HOME/.cache/go
	fi

	LANG_DIR_PYTHON=$PLAN9/langs/python3
	if [ -d $LANG_DIR_PYTHON ]; then
		$LANG_DIR_PYTHON/bin/python3 -m venv $PLAN9/langs/venv
	fi
fi

