#!/usr/bin/env bash

export PLAN9=/usr/local/plan9
export SHELL=/usr/local/plan9/bin/rc
export acmeshell=$SHELL
export tabstop=4
export TERM=dumb
export PAGER=cat
export BROWSER=xdg-open
export PATH="$PLAN9/usrbin:$PLAN9/langs/ruby/bin:$PLAN9/langs/go/bin:$PLAN9/langs/python3/bin:$PATH:$PLAN9/bin"
export font=/mnt/font/GoMono/10a/font
#export font=/mnt/font/BerkeleyMonoTrial-Regular/11a/font
export EDITOR=E


if [ "$(pgrep -x plumber)"  ];  then
	echo "Plumber is already running"
else
	$PLAN9/bin/plumber
	cat "$PLAN9/plumb/basic" | $PLAN9/bin/9 9p write plumb/rules
fi


$PLAN9/bin/acme -af $font &


# use -b to preseve area of typing when clicked but  it's annoying sometimes